### ISSUE TITLE
Investigate if serde and text_io dependencies are necessary

### ISSUE THREAD

**Issue by simeg** [simeg/eureka#20]
~~I think `serde` is being used because initially it was planned to have one JSON file with all config, but then it was decided to keep them separate. And I think `serde` just stayed after that.~~ `serde` is no longer a dependency, see #21.

`text_io` deals with user input. One macro is being used from the dependency and it feels like user input can be dealt with without an external dependency.

**Comment by oversoul** [comment]
i looked at the code, i dont see text_io anywhere, could be wrong.

**Comment by simeg** [comment]
@oversoul You are correct! I removed `text_io` in 1.6.0 and reduced binary size by 0.02 kB 😄

**Comment by oversoul** [comment]
@simeg damn!
