### ISSUE TITLE
No new line at the end of the file

### ISSUE THREAD

**Issue by lpolaright** [simeg/eureka#3]
👽 
https://github.com/simeg/eureka/blob/5c6f362de0cd89fb447e0cb8fa48bc3cf88e16e6/src/main.rs#L299

**Comment by simeg** [comment]
There is a new line there, otherwise it would show [this](https://programminghistorian.org/images/getting-started-with-github-desktop/getting-started-with-github-desktop-2.png) little red icon at the bottom.
