### ISSUE TITLE
is vim available in all destros ?

### ISSUE THREAD

**Issue by iamaamir** [simeg/eureka#38]
https://github.com/simeg/eureka/blob/81b6a7e74ddf9d858cc11acc03891750ee03c15e/src/main.rs#L136

most of the systems i have used are using vi for vim even on my ubuntu 18 there is nothing like vim but there is vi

in most cases user will have install vim

![Command 'vim' not found, but can be install](https://user-images.githubusercontent.com/8420386/50770855-bf9f2c00-12ae-11e9-981a-176b6481d82f.png)

so i'll prefer to use /usr/bin/vi

![ls | grep ^vi](https://user-images.githubusercontent.com/8420386/50770331-ea888080-12ac-11e9-8162-9fbeff043ebf.png)

**Comment by simeg** [comment]
Hi @iamaamir! Sure, the popular distros have vim symlinked to vi anyway so that is a good idea.

As a future improvement we could assert what binaries are available before offering the options, but right now this project is a MVP.

I'll make the change and deploy a new version soon.

**Comment by simeg** [comment]
Version 1.5.2 was just released with these changes in it: https://github.com/simeg/eureka/commit/52973d30faae61a8ae0f63424a2c514392345ffa
