### ISSUE TITLE
Only show available editors with correct path in list

### ISSUE THREAD

**Issue by simeg** [simeg/eureka#40]
**Background**
(#38, #39)
This project is written for macOS (because me, the author, uses a Mac) but not every user uses macOS. On Ubuntu the path to `nano` is different from macOS.

**Proposed solution**
Before showing the user the list of editors, we should "query" the system to see what binaries are available at what locations.

**Note**: If the command `which [editor]` returns `0` we can 1) _know that the binary exists on the system_, and 2) _we get the path_. So `which` would be a good command for this.

**Comment by iamaamir** [comment]
which  returns  the  pathnames of the files (or links) and It does this by searching the PATH, you could search the [$PATH](https://doc.rust-lang.org/std/env/fn.split_paths.html) and then walk the dirs to.

another trick could be just run the command with `-v` if we got back something meaning command is present.

or the better is to use [a crate](https://crates.io/crates/which)

**Comment by simeg** [comment]
Yeah, we could search the PATH directly.

Ideally I wouldn't want to add a dependency for this, but because it's cross-platform I think I'd be OK with it. I have no idea how the rest of this tool works on Windows though.

**Comment by iamaamir** [comment]
these tools are *nix olny so it would be better to use a crate

**Comment by simeg** [comment]
Redundant after #36
