### ISSUE TITLE
[Question][Offtopic] Terminal and colorscheme 

### ISSUE THREAD

**Issue by ngortheone** [simeg/eureka#42]
Hi, I like your terminal color scheme on gif.
What terminal do you use and what color scheme is on that gif?

**Comment by simeg** [comment]
Hi @ngortheone!

I have all [my dotfiles on Github](https://github.com/simeg/dotfiles).

More specifically you can find where I use the color theme [here](https://github.com/simeg/dotfiles/blob/master/zsh/.zshrc#L18). And the prompt theme you can find [here](https://github.com/simeg/lambda-pure).

I use a custom prompt theme which is a duplicate of [this prompt](https://github.com/marszall87/lambda-pure), but I wanted to be able to not show the NodeJS version. Although now that version is up to date with my fork, so you could use that one. See `PURE_NODE_ENABLED` to disable the NodeJS version.

I'll close this and for more questions please submit an issue in my dotfiles repo 🙂
