### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by murlakatamenka** [simeg/eureka#43]
Configuration files are expected to be in `~/.config/eureka/` / `$XDG_CONFIG_HOME/eureka/` per XDG Base Directory Specification instead of `~/.eureka/`

---

Summary of the spec is on Arch Wiki:
https://wiki.archlinux.org/index.php/XDG_Base_Directory

The full specification is here:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Thanks.

**Comment by simeg** [comment]
Makes sense!

**Comment by simeg** [comment]
Fixed in #50.

**Comment by xeruf** [comment]
Has been unfixed, please fix again or reopen the issue to indicate the current state!

**Comment by simeg** [comment]
There's a fix available for it, but I reverted it because I felt like I would break the tool for people upgrading to new versions. Maybe that's ok though?

WDYT?

**Comment by xeruf** [comment]
I think the only important configuration left is the ideas repo, so I don't think it would be much of a problem to break compatibility. You could also simply check for the existence of the `.eureka` dir and move it to its new location on app start, and remove that code again for the following version.

**Comment by simeg** [comment]
Yeah that was my idea to make the tool move the config, just never got around to doing it. Maybe now after the code is easier to work with I'll give it a go.

**Comment by simeg** [comment]
I will include this in the next major version, see #90

**Comment by simeg** [comment]
Fixed in version 2.0.0

**Comment by murlakatamenka** [comment]
Thanks! 👍
