### ISSUE TITLE
GCC Compile FAIL

### ISSUE THREAD

**Issue by hsmyers** [simeg/eureka#49]
After:
`t_backtrace_open+0x39): more undefined references to __errno follow`
there follows:
`error: aborting due to previous error`
`error: failed to compile eureka v1.6.1`
and:
`Caused by:`
`Could not compile 'eureka'.`

Attempted to update with:
`C:\>cargo install eureka --force`

**Comment by simeg** [comment]
You're on Windows yes? I don't have access to Windows so can't really debug and what you provided is not enough to pinpoint the problem.

This is the significant change that's in 1.6.1: https://github.com/simeg/eureka/commit/61d8feaa7688d3d94e3cebd970ad7ee7c0bc0175

Can you debug on your own or provide more info?

**Comment by simeg** [comment]
Closing this as no update from @hsmyers in a few months. Feel free to re-open.
