### ISSUE TITLE
Improvement - create an .md for every idea, and have the README as a table of contents

### ISSUE THREAD

**Issue by lpolaright** [simeg/eureka#6]
So instead of eureka just opening the README file, maybe it should create a new eureka file, and append to the README the link to that eureka.

So the use case would look something like:
`eureka` ->
Q: `What subject would you like? `
A: `Card Mechanicle`

Which would create a file called - `CARD_MECHANICLE.MD`
and append a link to it from the `README.MD`, once ofcourse you finish writing the contents with VIM.

**Comment by simeg** [comment]
I'll close this issue because I don't think it's usable to have to navigate between multiple files to read your files, for more context see #31.
