### ISSUE TITLE
Support for alternative branch names

### ISSUE THREAD

**Issue by booniepepper** [simeg/eureka#63]
It's a bit of a political hot topic right now, but I'm seeing that in the near future it might not be possible to assume users or repositories default to `master`.

- https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
- https://gitlab.com/gitlab-org/gitlab/-/issues/221164

I propose moving the branch name out to something that can be configured rather than a hard-coded string of "master".

**Comment by booniepepper** [comment]
As a personal note, I don't have a lot to say about the word "master" itself. A lot of people are expending a lot of energy talking about it and I'll leave them to it. I think there are good points on the relation to slavery in the English language, and also on the usage and utility of the term outside of that context.

For me, I actually just like to name my branches something fun. But I think the general development community's sentiment is going to roll toward less usage of the word "master" in a git context.

**Comment by simeg** [comment]
Hi @hiljusti.

Thanks for bringing it up! Sounds like a good idea to make it configurable. I agree I don't have much to contribute to the discussions, but I generally believe that things that makes people feel bad should be addressed.

I'll try to find time soon to do this!

**Comment by simeg** [comment]
Fixed in #66. Will be available in `1.8.0`.
