### ISSUE TITLE
Why so complicated?

### ISSUE THREAD

**Issue by xeruf** [simeg/eureka#64]
I considered installing this application, but considering the amount of setting up, getting used to and all the code I am seeing, I thought I'd be better off with a simple shell script. This is what I came up with:

```sh
#!/bin/sh
p=$PWD
cd $HOME/data/notes
case $1 in
log) file=life/${2:-general};;
idea) file=idea/$2.md;;
write) file=writings/$2.md;;
*) file=$2.md;;
esac
test "$3" && echo $3 >>$file || $EDITOR $file
git add $file
git commit -m $file
git push
cd $p
```

What is the reason for all that code, what more is your application doing?

**Comment by simeg** [comment]
Hello. Why the negative attitude? :/ I never said this application is doing anything more than any script is capable of. Feel free to use your script.

**Comment by xeruf** [comment]
Oh, this wasn't meant negatively :) I was merely confused why you have so much code for a seemingly trivial task, whether there are some features I am unaware of that warrant the complexity.
