### ISSUE TITLE
Does not respect alternate branch names

### ISSUE THREAD

**Issue by dbearden** [simeg/eureka#70]
The push function still assumes that the branch name is "master." This causes a panic when saving a new idea, especially when following certain newer branch naming conventions (e.g., "main" instead of "master).
https://github.com/simeg/eureka/blob/a8cac6d4269dfb098d28a7e7e08ceaab9a5f128a/src/git.rs#L49

**Comment by simeg** [comment]
Yep, thanks for reporting. I'll take a look.
