### ISSUE TITLE
Path must be absolute Issue

### ISSUE THREAD

**Issue by mtmfahathdev** [simeg/eureka#95]
Hi, I am getting the following error when I try to configure my repo.

![image](https://user-images.githubusercontent.com/76448136/173222172-21dda4dd-9878-4a75-b333-9673e1eca767.png)

**Comment by simeg** [comment]
Hi!

The absolute path is for the repo on your local machine. So something like `/Users/simon/repos/ideas`. But I can see how it's confusing. The tool should support both local and remote repos. It's tracked in #94.

Feel free to re-open if any more questions!
